version: "3.8"

services:
  nginx:
    image: nginx_rcabezas
    ports:
      - "443:443"
      - "9000:9000"
    volumes:
      - /home/rcabezas/data/wordpress
  mariadb:
    image: mariadb_rcabezas
    ports:
      - "3306:3306"
    volumes:
      - /home/rcabezas/data/db
  wordpress:
    image: wordpress_rcabezas
    ports:
      - "9000:9000"
      - "3306:3306"
    volumes:
      - /home/rcabezas/data/wordpress