version: "3.9"
services:
  nginx:
    image: nginx_rcabezas
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
  mariadb:
    image: mariadb_rcabezas
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    #volumes:
    #  - /Users/rcabezas/data/db:/var/lib/mysql
  wordpress:
    image: wordpress_rcabezas
    container_name: wordpress
    environment:
      MARIADB_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWD: ${MYSQL_PASSWORD}
    ports:
      - "9000:80"
    #volumes:
    #  - /Users/rcabezas/data/wordpress:/usr/share/webapps/wordpress