version: "3.9"
services:
  nginx:
    image: nginx_rcabezas
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - wordpress:/usr/share/webapps
  mariadb:
    image: mariadb_rcabezas
    container_name: mariadb
    env_file: .env
    restart: always
    volumes:
      - db:/var/lib/mysql
  wordpress:
    image: wordpress_rcabezas
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/usr/share/webapps

volumes:
  wordpress:
  db: