version: "3.9"
services:
  nginx:
    image: nginx_rcabezas
    container_name: nginx
    depends_on: 
      - wordpress
    networks: 
      - default
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - wordpress:/usr/share/webapps
  mariadb:
    image: mariadb_rcabezas
    container_name: mariadb
    networks: 
      - default
    env_file: .env
    restart: always
    volumes:
      - db:/var/lib/mysql
  wordpress:
    image: wordpress_rcabezas
    container_name: wordpress
    depends_on: 
      - mariadb
    networks:
      - default
    env_file: .env
    restart: always
    volumes:
      - wordpress:/usr/share/webapps

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rcabezas/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rcabezas/data/db

networks: 
  default: